// export const selectLightTheme = (state)=>state.lightTheme
// export const selectIsLoading = (state)=>state.isLoading
// export const selectIsError = (state)=>state.isError
// export const selectIsLogin = (state)=>state.isLogin
// export const selectIsDelate = (state)=>state.isDelate
// export const selectIsRegister = (state)=>state.isRegister
// export const selectIsVerified = (state)=>state.isVerified
// export const selectToken = (state)=>state.token
// export const selectTefreshToken = (state)=>state.refreshToken
// export const selectSesionId  = (state)=>state.sesionId
// export const selectUserName = (state)=>state.userName
// export const selectEmail = (state)=>state.email
// export const selectBalance = (state)=>state.balance
// export const selectTotalIncome = (state)=>state.totalIncome
// export const selectTotalExpense = (state)=>state.totalExpense
// export const selectIncomes = (state)=>state.incomes
// export const selectIncomesCat = (state)=>state.incomesCat
// export const selectIncomesStat = (state)=>state.incomesStat
// export const selectExpense = (state)=>state.expense
// export const selectExpenseCat = (state)=>state.expenseCat
// export const selectRxpenseStat = (state)=>state.expenseStat
// export const selectTransactionData = (state)=>state.TransactionData 